### ISSUE TITLE
TypeScript Error: Type 'P' does not satisfy the constraint 'Params'. Type 'P' is not assignable to type 'ParamsArray'.

### ISSUE THREAD

**Issue by nathan815** [arb/celebrate#203]
- `node` version - 13.14.0
- `celebrate` version - 13.0.4
- `joi` version (via `npm ls --depth=0 | grep joi`) - 17.3.0
- `express` version - 4.17.1
- `@types/express` version - 4.17.6

My `joi` schema looks like this:

*not applicable*

The issue I am having with `celebrate` is:

I am getting this Typescript compilation error as soon as I import celebrate:

```
node_modules/celebrate/lib/index.d.ts(26,77): error TS2344: Type 'P' does not satisfy the constraint 'Params'.
  Type 'P' is not assignable to type 'ParamsArray'.
node_modules/celebrate/lib/index.d.ts(40,23): error TS2344: Type 'P' does not satisfy the constraint 'Params'.
  Type 'P' is not assignable to type 'ParamsArray'.
node_modules/celebrate/lib/index.d.ts(84,196): error TS2344: Type 'P' does not satisfy the constraint 'Params'.
  Type 'P' is not assignable to type 'ParamsArray'.
node_modules/celebrate/lib/index.d.ts(94,146): error TS2344: Type 'P' does not satisfy the constraint 'Params'.
  Type 'P' is not assignable to type 'ParamsArray'.
```

Not sure how exactly to fix this yet, but:

1. Here is the TS declaration in `celebrate/lib/index.d.ts:84`:
```
export declare function celebrate<P=ParamsDictionary, ResBody=any, ReqBody=any, ReqQuery=Query>(
   requestRules: SchemaOptions, joiOpts?: ValidationOptions, opts?: CelebrateOptions
): RequestHandler<P, ResBody, ReqBody, ReqQuery>;
                  ^
```
2. These generic declarations were introduced in PR #200 about a month ago.

**Comment by nathan815** [comment]
Mentioning @aarifkhamdi as author of #200.

**Comment by nathan815** [comment]
Workaround: downgrade celebrate to version 13.0.3.

```
npm install celebrate@13.0.3 --save-exact
```

**Comment by aarifkhamdi** [comment]
how can i reproduce this error? try to provide repository
maybe the parameter you are passing does not match the expected type

**Comment by nathan815** [comment]
Hi @aarifkhamdi thanks for the response. I'm not passing any parameters; the error is happening in celebrate's declaration file on line 84 (`lib/index.d.ts:84`) even without any code referencing celebrate.

Maybe it's a version issue? I am on express 4.17.1 (other versions are in first comment). The error goes away when I downgrade to celebrate 13.0.3 which is right before the generic types were introduced. I put a caret pointing at the type parameter causing the error in first comment.

 I dug through the types here and could not find exactly what is causing this. `RequestHandler` should accept a `ParamsDictionary` (P) type just fine. I'm not even sure where the type `ParamsArray` is coming in to the picture.

I'll try making a public repo to reproduce this.

**Comment by nathan815** [comment]
Looks like this problem was actually caused by `@types/express`. I was able to fix it by upgrading `@types/express` to 4.17.9 🙂 

Closing this issue.

**Comment by arb** [comment]
Should the type defs for express be included in celebrate to prevent this? I'm not super familiar with how other packages handle their type def files and dependencies.

**Comment by nathan815** [comment]
@arb I'm not sure if it would help since the application using celebrate still needs to have express and the express types package installed anyway. From what I read this has been a frequent issue with express and its types package.

**Comment by arb** [comment]
Right but I could move those type definition files into the formal `dependencies` so they are installed along with `celebrate`? I don't personally use TypeScript so I don't really have any real world experience dealing with these kinds of issues.
